title: Fang Chen # your name (or website title) here
logo: "/images/logo.mask.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi, this is Fang. <br/> 
  I define myself as a Genomics Data Scientist and currently work at Penn State Health Milton S. Hershey Medical Center. <br/>
  This is the Demo site for my projects and presentations. <br/>
  My personal site is: <a href="https://fangbucks.com/fangchen//">To Fang's homepage</a> 
  <br><br>
  rareGWAMA is awesome!! 
  <br><br>
  <a href="https://dajiangliu.blog/">To The Liu Lab</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
