title: Fang Chen # your name (or website title) here
logo: "/images/logo.mask.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Just DEMO 
  <br><br>
  rareGWAMA is awesome!! 
  <br><br>
  <a href="https://dajiangliu.blog/">To The Liu Lab</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
